<?php $this->load->view('/common/header'); ?>
<div class="about">
	<div class="container">
		<div class="about-grids">

<p>Cast India is a public access platform with an overall purpose to create portfolios, host websites and to create a community for aspiring models, actors, photographers, and agencies. Person to person display, marketing, and communication - these are the people who are offered Cast India services. These services are on a professional level between models, photographers and agents. Cast India does not own or claim on any personal portfolio content or images uploaded by an individual user for individual promotion and presentation. User must take the responsibility to abide by this agreement and site guidelines. </p>
<p>
By using services provided by Cast India you will be agreeing to the following terms and conditions which will governed by all its members and site users. You are also agreed to this contract between you, the user, and Cast India when you clicked the "I agree" box during the Signup process. Incase you aren't a member, just browse the website.</p>
<p>
Disclaimer: The services and the site contains information, facts and opinions that are received from different entities and organizations. The services and sites that have provided are on an "AS IS" basis without any warranties of any kinds, services either express or implied, including but not limited to warranties of title or implied warranties of merchantability or fitness for a particular purpose. Except those warranties which are imposed by and unable of exclusion. Restriction or modification that comes under the laws is applicable to this agreement. Neither Cast India nor its associates endorse or are responsible for the accuracy or reliability of any opinion, casting, job offer, advice or statement on the services or sites of Cast India.
</p>
<p>In accordance with the Children's Online Privacy Protection Rule, as a parent or guardian of a minor under the age of 16 you must have to read and agree to the terms of use and take full responsibility for the minor based on the information below. Cast India collects individual personal details like e-mail id, address, telephone number, age, height, weight, shoe size, physique, hair colour and eye colour of the children whose age is 16 or under directly in the Cast India sign up process. Some details of the child, like telephone no, e-mail id and exact address are not displayed publically. Only the details like major city location, height, weight, age, hair colour, and eye colour are displayed publically, only for the purpose of casting agents to view and contact the child for casting.
</p>
<p>Cast India will never disclose information which is not reasonably necessary to participate in an activity as a condition of participation. Agents as a third party may request information for a casting; Cast India will not disclose such information to agents without taking your prior permission via e-mail. Cast India is not responsible or liable for the action of these agents who are not under any contract or agreement with Cast India other than the terms and conditions set forth here. You can review, ask to have it delete and refuse to allow any further collection or use of the personal information. All you need to do is email us at customer.service@castindia.in and Cast India will handle such a request.</p>
<p>
The Cast India service and site contains features like portfolio booking forms, bulletin boards, forums, member messages, member comments which will allows you to post information, provide feedback to Cast India and its associates to interact in real time. You are agreed not to post or transmit any unlawful, fake, fraudulent, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, profane, hateful, racially, ethnically or any other objectionable material of any kind including but not limited to any material which encourages conduct that would constitute a criminal offence, violate the rights of others, any applicable local, state, national or international law. Any content posted in the member messages as a casting or solely by the user, and it is the full responsibility of the user and all recipients. </p>
<p>
Every member's email address is made private through the member messages. If any e-mail is posted in the member message, and if it is done by without any prior approval of Cast India, it would be against the messaging policy of Cast India. Any acceptance, correspondence or agreement is solely done by the users and recipient's, it is their responsibility only. Cast India divisions, associates, agents, representatives, or licensors make no depiction to the legitimacy of any agency and shall not be liable to anyone for any loss, injury, direct or indirect incidental, consequential, special, and disciplinary or similar damages that may arise from received or sent information, either directly or indirectly through the member messages. In addition you agree to not to post any information or correspondence that is not of a professional environment or one which contravenes US Federal, and International Trademark or copyright laws and restrictions in any way.</p>
<p>
You will be responsible to insure and hold Cast India harmless, its subsidiaries, divisions, associates, agents, and representatives. Cast India will not be responsible for the loss of any material you posted or transmitted. Even though Cast India and its associates monitor and review each and every discussions, chats, postings, transmissions, and bulletin boards on the site, neither Cast India and nor its associates are under any obligation to do so. Cast India reserves the rights to change or modify portfolio content or information or message board postings as whenever needed and without any notice. You must acknowledge that the Cast India and its associates do not control the information available on the bulletin board or any opinion, advice, statements, services, offer or any other information or content presented on any bulletin board of their respective solely liable authors. Cast India and its associates reserve the rights at their sole preference to edit, refuse to post, or to remove any material, links, email addresses, images, content which was submitted to be posted on bulletin boards, or portfolios. Cast India and its associates reserve the rights at their sole preferences to deny access to email systems provided for general communication purpose.</p>
<p>
Cast India has its own guidelines regarding posting of appropriate images, email addresses, content, and links. You agreed to read and follow the guidelines properly which are posted throughout the website. Whenever you use services and the sites of Cast India, use it at your own risk. Cast India and its associates, subsidiaries, divisions, agents, representatives or licensors shall not be liable to you or anyone for any of the loss or injury or any direct or indirect incidental, consequential, special, punitive, or similar damages which could have arisen out of your access or use, your inability to access or use the services and sites and the information available at on the site or service and action that is taken in response to result of any information available on the service or site. You hereby can waive any and all claims against Cast India, its associates, subsidiaries, divisions, agents, representatives or licensors which may have arisen out of your use of the service and site and information available regarding it. Cast India will not be responsible for any refunds of PayPal payments or any withdrawals. It is the responsibility of the user to cancel the future payments as per instructions regarding PayPal and Cast India, its associates, subsidiaries, divisions, agents, representatives or licensors. The compensation arises out of your use of the services and sites and the information available regarding it.</p>
<p>
Any communication or material that you post or transmit to the service or on the site is and always will be treated as a non-confidential and non-proprietary. You must take full responsibility for anything that you post or transmit, and you can grant Cast India and its associates right to edit, copy publish and distribute information that you post or transmit for any purpose.</p>
<p>
Cast India and its associates do not review or monitor any web sites that are linked to the service or from personal portfolio on this site. If you click on the link of personal pages from Cast India, that means all users of the system acknowledge that, Cast India is not responsible for the accuracy or content of those links. You agreed not to post URL's and other website links in any form into your personal home page section. You will also not post URL, links or text which leads to Adult Sites or Pay Sites. Cast India also reserves the rights to remove portfolios which contain adult sites or pay sites from the site without any notice. Additional certain links to the sites are determined time to time by Cast India. The use of HTML formatting and scripting in certain portfolios must be like determined by Cast India, or else it may not be permitted to be include such things in a portfolio. </p>
<p>
Cast India is not under any obligation to provide exposure to any contending site through links or any other method in portfolio and Cast India may remove these things at its own discretion without any notice. The Cast India referral system is intended for work related offers and general inquires related to work. Use of referral system for promotion of services and goods is not an ideal and appropriate to referral system. Cast India permits one main member portfolio per person. Managers, agents, and photographer who have entitled to post on behalf of their clients, may control Model and Actor portfolio.
It is against Cast India policy to allow any competitors portfolio sites to solicit Cast India members from an account at Cast India. Any Competing portfolio sites or online agency site that sign up at Cast India either as a free member account or paid upgraded account, and actively solicits Cast India members to join competing website or agency. They also can deactivate their account at Cast India without any refund.</p>
<p>
The promotion and recruitment of Escorts, Escort Services, Personal Companies are contrary purpose of Cast India and will not be tolerated in any fashion. Soliciting for recruitment or offering the services of escort is strictly prohibited on this site. Portfolios that are mainly used for the solicitation or promotion of escort services will be disabled immediately without any refund. This includes (is not limited): Use of referral system, hyperlinks to external sites, promoting escorts, URL's (Web addresses) promoting escorts or any other such kind of activity that staff of Cast India deems as a solicitation, promotion or offers. </p>
<p> 
Cast India has a stated policy regarding the posting of sexually explicit images on its web pages. Sexually explicit images are not permitted on Cast India's site. Sexually explicit images include but are not limited to images of sexual intercourse; obvious states of sexual arouse (erection), or over sexual positions (such as noticeable visible or spread genitalia). Failure to follow this restriction will result in the removal of images. And one can get its member portfolio disabled. Consistent misclassification or categorization of images may result in the force setting of ratings and that may result in the removal of portfolio.</p>
<p>
Cast India does not support bandwidth theft. If anyone found linking images from Cast India to other site, or misusing links from other site to Cast India, or copying content from Cast India, or inappropriate linking to Cast India (to increase their site's view through hidden frames) will result in permanent removal from Cast India without any notice and may necessitate the notification of the appropriate State or Federal authorities.</p>
<p>
You must know that if you voluntarily disclose any personal information (e.g. username, email id) on a bulletin boards, and if that information collected and used by others that may result in unsolicited messages from other parties, shall therefore be the sole responsible and liable for the poster.
As a member of Cast India, you will receive regular email updates and you will be contacted by other system members who are seeking to work with you. You will receive emails frequently from Cast India. As new features or member programs and promotions are developed and launched, you will be informed via email and also by the posting of sites. We venture to limit email contact as much as possible from the system administrators. If whenever email is sent and returned with a bad email address, we will try to locate a correct address from any linked website. And hence, your portfolio will be disabled. If your portfolio has been disabled, please contact us with correct email address and we will re-activate your portfolio.</p>
<p>
This user agreement and any disputes arising out of or related to the service and site shall be governed by, and construed and enforced in accordance with International laws. This site constitutes your agreement to, but not limited to, the current condition that is listed in the agreement.
If you are 16 years old or younger, you must have a parent or a legal guardian with you to approve all information and you must ensure that the parent or legal guardian's email address and contact information is used at all times. Cast India reserves the right to change and modify these usage rules as appropriate and without any notice.</p>
<p>
Violation of these Terms and Conditions will harm your membership, and it can be terminated. Please Note: By signing up for any our services you agree to be bound by all Cast India terms and conditions.

</p>
</div>
</div>
</div>
<?php $this->load->view('/common/footer'); ?> 